name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm turbo lint

      - name: Type Check
        run: pnpm turbo type-check

      - name: Build
        run: pnpm turbo build

  # mobile-build:
  #  runs-on: ubuntu-latest
  #  strategy:
  #    matrix:
  #     flavor: [admin, user, driver, guest]
  #steps:
  #- uses: actions/checkout@v4

  #- uses: pnpm/action-setup@v2
  #with:
  #version: 9

  #- run: pnpm install

  #- name: Build mobile flavor
  #run: pnpm --dir apps/mobile run build:${{ matrix.flavor }}
